// Generated by ReScript, PLEASE EDIT WITH CARE


var formNode = document.querySelector("#form");

var messageNode = document.querySelector("#message");

var shiftNode = document.querySelector("#shift");

var encryptNode = document.querySelector("#encrypt");

var decryptNode = document.querySelector("#decrypt");

var alphabet = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z"
];

function ceaserCipherInterpretor(text, shift, mode) {
  
}

var message = "";

var shift = "";

export {
  formNode ,
  messageNode ,
  shiftNode ,
  encryptNode ,
  decryptNode ,
  alphabet ,
  message ,
  shift ,
  ceaserCipherInterpretor ,
  
}
/* formNode Not a pure module */
