// Generated by ReScript, PLEASE EDIT WITH CARE


var formNode = document.querySelector("#form");

var messageNode = document.querySelector("#message");

var shiftNode = document.querySelector("#shift");

var encryptNode = document.querySelector("#encrypt");

var decryptNode = document.querySelector("#decrypt");

var displayNode = document.querySelector("#display");

var alphabet = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z"
];

function getIndexOfLetter(letter) {
  return alphabet.indexOf(letter);
}

function getAdjustedIndex(index, mode) {
  if (mode) {
    if (index < 0) {
      return index + 25 | 0;
    } else {
      return index;
    }
  } else if (index > 25) {
    return index - 25 | 0;
  } else {
    return index;
  }
}

function ceaserCipherInterpretor(text, shift, mode) {
  var textAsArray = text.toUpperCase().split("");
  var shiftAsInt = (parseInt(shift));
  if (mode) {
    var decryptedTextArray = textAsArray.map(function (letterInArray) {
          var indexOfLetter = alphabet.indexOf(letterInArray);
          if (indexOfLetter !== -1) {
            return alphabet[getAdjustedIndex(indexOfLetter - shiftAsInt | 0, /* Decrypt */1)];
          } else {
            return " ";
          }
        });
    return decryptedTextArray.join("");
  }
  var encryptedTextArray = textAsArray.map(function (letterInArray) {
        var indexOfLetter = alphabet.indexOf(letterInArray);
        if (indexOfLetter !== -1) {
          return alphabet[getAdjustedIndex(indexOfLetter + shiftAsInt | 0, /* Encrypt */0)];
        } else {
          return " ";
        }
      });
  return encryptedTextArray.join("");
}

formNode.addEventListener("submit", (function (e) {
        return e.preventDefault();
      }));

encryptNode.addEventListener("click", (function (param) {
        var message = messageNode.value;
        var shift = shiftNode.value;
        if (message.length <= 0 || shift.length <= 0) {
          return (alert("You must enter a message or a shift value!"));
        }
        var encryptedMessage = ceaserCipherInterpretor(message, shift, /* Encrypt */0);
        displayNode.textContent = encryptedMessage;
        
      }));

decryptNode.addEventListener("click", (function (param) {
        var message = messageNode.value;
        var shift = shiftNode.value;
        if (message.length <= 0 || shift.length <= 0) {
          return (alert("You must enter a message or a shift value!"));
        }
        var decryptedMessage = ceaserCipherInterpretor(message, shift, /* Decrypt */1);
        displayNode.textContent = decryptedMessage;
        
      }));

export {
  formNode ,
  messageNode ,
  shiftNode ,
  encryptNode ,
  decryptNode ,
  displayNode ,
  alphabet ,
  getIndexOfLetter ,
  getAdjustedIndex ,
  ceaserCipherInterpretor ,
  
}
/* formNode Not a pure module */
