// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

var formNode = document.querySelector("#form");

var messageNode = document.querySelector("#message");

var shiftNode = document.querySelector("#shift");

var encryptNode = document.querySelector("#encrypt");

var decryptNode = document.querySelector("#decrypt");

var alphabet = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z"
];

function ceaserCipherInterpretor(text, shift, mode) {
  var textAsArray = "".split(text);
  if (mode) {
    throw {
          RE_EXN_ID: "Match_failure",
          _1: [
            "Index.res",
            64,
            2
          ],
          Error: new Error()
        };
  }
  Belt_Array.map(textAsArray, (function (letterInArray) {
          Belt_Array.getIndexBy(alphabet, (function (letterInAlphabet) {
                  return letterInAlphabet === letterInArray.toUpperCase();
                }));
          
        }));
  
}

var message = "";

var shift = "";

export {
  formNode ,
  messageNode ,
  shiftNode ,
  encryptNode ,
  decryptNode ,
  alphabet ,
  message ,
  shift ,
  ceaserCipherInterpretor ,
  
}
/* formNode Not a pure module */
