// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";

var alphabetArray = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z"
];

function convertLetterToCipher(letter, shift) {
  var indexOfLetter = alphabetArray.indexOf(letter);
  var indexOfCipher = Caml_int32.mod_(indexOfLetter + shift | 0, alphabetArray.length);
  return Caml_array.get(alphabetArray, indexOfCipher);
}

function convertCipherToLetter(letter, shift) {
  var indexOfLetter = alphabetArray.indexOf(letter);
  var indexOfLetter$1 = Caml_int32.mod_(indexOfLetter - shift | 0, alphabetArray.length);
  return Caml_array.get(alphabetArray, indexOfLetter$1);
}

var uncipheredMessage = "string";

export {
  uncipheredMessage ,
  alphabetArray ,
  convertLetterToCipher ,
  convertCipherToLetter ,
  
}
/* No side effect */
